on: [push]

jobs:
  test-s3-publish-action:
    runs-on: ubuntu-latest
    name: Test s3-publish-action
    steps:
      - uses: actions/checkout@v2
      - id: foo
        uses: Indellient/s3-publish-action@v0.1.1
        with:
          folder-name: 'master'
          bucket-name: ${{ secrets.bucket_name }}
